### ISSUE TITLE
作者的网站很棒,希望有一个返回 list json 的接口,可以 mock 加载更多,刷新 list 的这种需求

### ISSUE THREAD

**Issue by est7** [kuizuo/api-service#2]

**Comment by kuizuo** [comment]
很抱歉，我现在才看到该信息。

本网站并不是为了 mock 而生，而是将个人常用到的 api 服务整合到一起，通过 [api.xxx.com](http://api.xxx.com/) 来进行统一管理调用。

我猜测你所需要的功能是类似下滑加载更多的需求，这种的话则是根据请求方的 cursor 而定，然后随机返回一些数据。可以在 server/api下编写 mock.ts 来完成这一需求，其实就类似于 [jsonplaceholder](https://jsonplaceholder.typicode.com) 所提供的功能，我在 fake（假数据）下有接入该服务，只不过我添加了 3s 的缓存，可根据实际情况来修改。
